### ISSUE TITLE
Nothing in the extensions folder?

### ISSUE THREAD

**Issue by TomKranenburg** [danreeves/dt-exchange#57]
Sorry am I missing something? I pulled the source but there as nothing in the extensions folder. Perhaps I'm being dumb.

**Comment by danreeves** [comment]
Ah, the README needs updating since we stopped committing the built files. You can download the latest auto generated build from here: https://github.com/danreeves/dt-exchange/releases/tag/latest

Or you can follow the Development instructions to build the files into the extensions folder: https://github.com/danreeves/dt-exchange#development

**Comment by TomKranenburg** [comment]
Ahhh no problem. Great work by the way. I'm watching the releases.
